wappie/buildings/urls.py
from django.urls import path

from buildings.views import overview, building, floor_items, show_item, buildingLocation, \
    floor_rooms, room_info, floor_geojson

app_name = 'buildings'

urlpatterns = [
    path('', overview, name='index'),
    path('room', room_info, name='room_info'),
    path('rooms/', floor_rooms, name='floor_rooms'),

    path('json/', floor_geojson, name='geojson'),

    path('<slug:building_name>/', building, name='building'),
    path('<slug:building_name>/location', buildingLocation, name='building_location'),
    path('<slug:building_name>/<int:floor_number>', building, name='building_floor'),
    path('<slug:building_name>/<int:floor_number>/items', floor_items, name='floor_items'),

    path('item_details/', show_item, name='item_details'),

]

wappie/items/urls.py
from django.urls import path

from items.views import ItemUpdate, delete, replace, ItemCreate, history, items, export
from items.type_views import ItemTypeCreate, ItemTypeUpdate, item_type_delete

app_name = 'items'

urlpatterns = [
    path('', items, name='index'),

    # Items
    path('edit/<int:pk>', ItemUpdate.as_view(), name='edit'),
    path('delete/<int:pk>', delete, name='delete'),
    path('replace/<int:pk>', replace, name='replace'),
    path('add/', ItemCreate.as_view(), name='add'),
    path('history/<int:pk>', history, name='history'),
    path('export', export, name='export'),

    # Item Types
    path('types/add/', ItemTypeCreate.as_view(), name='add_type'),
    path('types/update/<int:pk>', ItemTypeUpdate.as_view(), name='update_type'),
    path('types/delete/<int:pk>', item_type_delete, name='delete_type'),
]

wappie/wappie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from wappie.views import index

urlpatterns = [
    # Home page
    path('', index, name='home'),

    # Apps
    path('buildings/', include('buildings.urls'), name='buildings'),
    path('items/', include('items.urls'), name='items'),

    # Admin
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wappie/items/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.postgres.fields import ArrayField
from geopy import Point

from netaddr import EUI, AddrFormatError
from simple_history.models import HistoricalRecords

from buildings.models import Floor, Room


def mac_validator(mac):
    """
    Method which validates the mac in question
    :param mac: address to validate
    :raises ValidationError: when address is invalid
    """
    try:
        return EUI(mac)
    except (ValueError, AddrFormatError, TypeError):
        raise ValidationError("%(mac)s is not a valid MAC address.",
                              code='invalid',
                              params={'mac': mac})


class ItemQuerySet(models.QuerySet):
    def items_without_location(self):
        return self.filter(floor__isnull=True)


class ItemType(models.Model):
    type = models.CharField(
        max_length=40,
        unique=True,
        verbose_name="Type of the item.",
        help_text="What type the item is, for example: WAP, or Dispenser"
    )
    image = models.FileField(
        upload_to='',
        default='items/wifi-icon.png'
    )

    def __repr__(self):
        return f"<ItemType: type: {self.type}>"

    def __str__(self):
        return self.type

    class Meta:
        ordering = ['type']


def get_generic_type():
    return ItemType.objects.get_or_create(type='Generic')[0].id


class Item(models.Model):
    """
    Generic Item model.
    """
    floor = models.ForeignKey(
        to=Floor,
        on_delete=models.PROTECT,
        related_name="item",
        blank=True,
        null=True,
        verbose_name="The floor of the item."
    )
    room = models.ForeignKey(
        to=Room,
        on_delete=models.PROTECT,
        related_name="item",
        blank=True,
        null=True,
        verbose_name="The room of the item."
    )
    type = models.ForeignKey(
        to=ItemType,
        on_delete=models.SET_DEFAULT,
        default=get_generic_type,
        null=False,
        verbose_name="Type of the item."
    )
    location = ArrayField(
        base_field=models.FloatField(),
        size=2,
        # Can be blank or null: if a WAP is created but has no location yet
        blank=True,
        null=True,
        verbose_name="location",
        help_text="Enter two numbers (geolocation), seperated with a comma."
    )
    location_description = models.TextField(
        blank=True,
        null=True,
        verbose_name="location description",
        help_text="Textual description of the location."
    )
    start_date = models.DateTimeField(
        verbose_name="start date",
        help_text="The datetime the item was put here"
    )
    end_date = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="end date",
        help_text="The datetime of the end of the item."
    )
    remarks = models.TextField(
        null=True,
        blank=True,
        verbose_name="remarks",
        help_text="Any possible remarks."
    )
    mac = models.CharField(
        max_length=17,
        unique=True,
        null=False,
        verbose_name="mac address",
        help_text="mac address of the wap"
    )
    history = HistoricalRecords()

    objects = ItemQuerySet.as_manager()

    def save(self, *args, **kwargs):
        self.clean()
        self.full_clean()  # We need a full_clean so it will validate the location
        super().save(*args, **kwargs)

    def clean(self):
        super().clean()
        self.mac = mac_validator(self.mac)
        self.check_correct_location()
        self.check_no_location_without_floor()
        self.check_room_is_in_floor()
        self.check_no_room_without_floor()

    def check_correct_location(self):
        try:
            if self.location:
                lat = self.location[0]
                lon = self.location[1]
                point = Point(latitude=lat, longitude=lon)
                self.location = (point.latitude, point.longitude)
        except (TypeError, KeyError, ValueError, IndexError):
            raise ValidationError(f"Location was of incorrect format.")

    def check_no_location_without_floor(self):
        if self.floor is None and self.location:
            raise ValidationError(f"Location is given yet floor is not given.\n"
                                  f"In order to choose a location, a floor must be given.")

    def check_room_is_in_floor(self):
        if self.room is not None and self.room.floor != self.floor:
            raise ValidationError(f"The given room ({self.room}) should be in the the given "
                                  f"floor ({self.floor}).")

    def check_no_room_without_floor(self):
        if self.room and not self.floor:
            raise ValidationError(f"If a room is given (now {self.room}), the floor should be given"
                                  f" as well.")

    def __str__(self):
        return f"{self.type}, at {self.location} on {self.floor}"

    def __repr__(self):
        location_text = "no floor"
        if self.floor:
            location_text = f"at {self.location} on {self.floor.building.abbreviation}." \
                            f"{self.floor.floor_number}"

        return f"<Item: {self.type} at " \
               f"{location_text}, " \
               f"from {self.start_date} to {self.end_date}>"

wappie/items/forms/create_item_type.py
from django import forms

from items.models import ItemType


class ItemTypeCreateForm(forms.ModelForm):
    class Meta:
        model = ItemType
        fields = ['type', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class ItemTypeUpdateForm(forms.ModelForm):
    class Meta:
        model = ItemType
        fields = ['type', 'image']

    def __init___(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

wappie/items/forms/item_forms.py
from django import forms

from buildings.models import Room
from items.models import Item


class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['type', 'floor', 'room', 'location', 'location_description', 'start_date', 'mac']

    def __init__(self, *args, **kwargs):
        super(ItemCreateForm, self).__init__(*args, **kwargs)
        self.fields['room'].queryset = Room.objects.none()

        if 'floor' in self.data:
            try:
                floor_id = int(self.data.get('floor'))
                self.fields['room'].queryset = Room.objects.filter(floor_id=floor_id).order_by('room_code')
            except (ValueError, TypeError):
                pass


class ItemUpdateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['type', 'floor', 'room', 'location', 'location_description', 'start_date', 'mac']

    def __init__(self, *args, **kwargs):
        super(ItemUpdateForm, self).__init__(*args, **kwargs)
        if 'room' not in self.data:
            self.fields['room'].queryset = Room.objects.none()

        if 'floor' in self.data:
            try:
                floor_id = int(self.data.get('floor'))
                self.fields['room'].queryset = Room.objects.filter(floor_id=floor_id).order_by('room_code')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            if self.instance.floor:
                self.fields['room'].queryset = self.instance.floor.rooms.order_by('room_code')

wappie/items/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone
from django.views import View

from buildings.models import Floor
from items.exceptions import SessionNotSetException
from items.exporter import ItemResource
from items.forms.item_forms import ItemCreateForm, ItemUpdateForm
from items.models import Item, ItemType

SUPPORTED_FORMAT = ['csv', 'json', 'xls', 'yaml', 'html', 'ods']


def items(request):
    items = Item.objects.all()
    item_types = ItemType.objects.all()
    return render(request, 'items/items.html', {'items': items, 'item_types': item_types,
                                                'formats': SUPPORTED_FORMAT})


def showItem(request, item_name):
    item = get_object_or_404(Item, name=item_name)
    return HttpResponse(",".join([str(item)]))


def replace(request, pk):
    item = Item.objects.get(id=pk)
    item.end_date = timezone.now()
    replace_item = Item()
    replace_item.start_date = timezone.now()
    replace_item.location = item.location
    replace_item.type = item.type
    replace_item.location_description = item.location_description
    replace_item.floor = item.floor
    replace_item.room = item.room
    replace_item.mac = item.mac
    item.delete()
    replace_item.save()
    return redirect('/items/edit/' + str(replace_item.id))


def delete(request, pk):
    item = Item.objects.get(id=pk)
    item.end_date = timezone.now()
    item.save()
    item.delete()
    return redirect('/buildings/')


def get_information_from_get_request(request):
    lon = request.get('lon')
    lat = request.get('lat')
    building_name = request.get('buildingName')
    floor_number = request.get('floorNumber')
    floor = None
    if building_name and floor_number:
        floor = Floor.objects.get(building__name=building_name, floor_number=floor_number)
    return lon, lat, floor


def history(request, pk):
    item = Item.objects.get(id=pk)
    item_history = item.history.all()
    history_list = [_build_neat_history_overview(entry) for entry in item_history]
    return JsonResponse(history_list, safe=False)


def _build_neat_history_overview(history_entry):
    try:
        lon, lat = history_entry.location
    except ValueError:
        lon, lat = '', ''
    return {'type': str(history_entry.type.image),
            'floor': str(history_entry.floor),
            'room': str(history_entry.room),
            'lat': lat,
            'lon': lon,
            'mac': history_entry.mac,
            'description': history_entry.location_description,
            'date of change': history_entry.history_date.strftime('%Y-%m-%d'),
            'time of change': history_entry.history_date.strftime('%H:%M:%S %Z')}


class ItemCreate(View):
    def get(self, request, *args, **kwargs):
        lon, lat, floor = get_information_from_get_request(request.GET)

        if floor:
            self.request.session['building_name'] = floor.building.name
            self.request.session['floor_number'] = floor.floor_number
        else:
            self.request.session.pop('building_name', None)
            self.request.session.pop('floor_number', None)

        form = build_create_form(lat, lon, floor)
        return render(request, 'items/item_add_form.html',
                      {'form': form})

    def post(self, request, *args, **kwargs):
        if request.POST.get('cancel'):
            return redirect(self.get_success_url())
        f = ItemCreateForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect(self.get_success_url())
        return render(request, 'items/item_add_form.html', {'form': f})

    def get_success_url(self):
        try:
            kwargs = get_kwargs_of_building(self.request.session)
            return reverse('buildings:building_floor', kwargs=kwargs)
        except SessionNotSetException:
            return reverse('buildings:index')


def build_create_form(lat, lon, floor):

    form = ItemCreateForm(initial={
        'location': f"{lat},{lon}" if lat and lon else '',
        'start_date': timezone.now(),
        'floor': floor})
    return form


class ItemUpdate(View):
    model = Item
    form_class = ItemUpdateForm
    template_name_suffix = '_update_form'

    def get(self, request, *args, **kwargs):
        item_id = kwargs['pk']
        item = Item.objects.get(id=item_id)

        lon, lat, floor = get_information_from_get_request(request.GET)
        form = build_update_form(floor or item.floor, item, lat, lon)
        return render(request, 'items/item_update_form.html',
                      {'form': form})

    def post(self, request, *args, **kwargs):
        if request.POST.get('cancel'):
            return redirect(self.get_success_url())
        elif request.POST.get('delete'):
            Item.objects.get(id=kwargs['pk']).delete()
            return redirect(self.get_success_url())
        if request.is_ajax():
            item, location, date = get_information_from_post_request(request.POST)
            if location and not item.floor:
                return
            item.location = location
            item._history_date = date
            item.save()
            return HttpResponse()
        form = ItemUpdateForm(request.POST, instance=Item.objects.get(id=kwargs['pk']))
        if form.is_valid():
            form.save()
            return redirect(self.get_success_url())
        return render(request, 'items/item_update_form.html', {'form': form})

    def get_success_url(self):
        try:
            kwargs = get_kwargs_of_building(self.request.session)
            return reverse('buildings:building_floor', kwargs=kwargs)
        except SessionNotSetException:
            return reverse('buildings:index')


def build_update_form(floor, item, lat=None, lon=None):
    location = f"{lat},{lon}" if lat and lon else None
    form = ItemUpdateForm(initial={'floor': floor, 'location': location or item.location,
                                   'room': item.room},
                          instance=item)
    return form


def get_information_from_post_request(request):
    lat = request.get("lat", "")
    lon = request.get("lon", "")
    date = request.get("date", "")
    item_id = request.get("id", "")
    item = Item.objects.get(id=item_id)
    location = [lat, lon]
    return item, location, date


def get_kwargs_of_building(session):
    fields = ['building_name', 'floor_number']
    if all(key in session for key in fields) and all(session[key] for key in fields):
        return {key: session[key] for key in fields}
    raise SessionNotSetException("Not all fields were set in the users's session.")


def export(request):
    export_format = request.GET.get('format')
    output = ItemResource().export(Item.objects.all())
    try:
        response = HttpResponse(getattr(output, export_format),
                                content_type='application/force-download')
        response['Content-Disposition'] = f'attachment; ' \
                                          f'filename="item_dump_{timezone.now().isoformat()}.{export_format}"'
        return response
    except AttributeError:
        return redirect('items:index')

wappie/templates/items/item_add_form.html
{% extends 'default.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block html_title %}
    {{ block.super }} - Add Item
{% endblock %}

{#{% block content_title %}Edit Item{% endblock %}#}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/bootstrap-datetimepicker.css' %}">
{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script src="{% static 'scripts/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'scripts/items/items.js' %}"></script>
{% endblock %}

{% block body_left %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

<form method="post" action="/items/add/" id="itemForm" item-room-url="{% url 'buildings:floor_rooms' %}" room-location-url="{% url 'buildings:room_info' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
    <input type="submit" value="Cancel" class="btn btn-secondary" name="cancel">
</form>


{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
    $(document).ready(function() {
        $(".datetimeinput").datetimepicker({
            format: "yyyy-mm-dd hh:ii:ss"
        });

        fillRoomsIfFloorExists();
        getRoomsOfFloor();
        fillLocationWhenFloorIsSelected();
    });
</script>
{% endblock %}

wappie/templates/items/item_types.html
{% extends 'default.html' %}
{% load static %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/items/items.css' %}">
{% endblock %}


{#{% block content_title %}Items{% endblock %}#}

{% block body_main %}


    <div class="row">
        <div class="col">
                <div id="table" class="table-editable">
                  <span class="table-add float-right mb-3 mr-2"><button type="button" class="btn btn-success btn-rounded btn-sm my-0">Add</button></span>
                  <table class="table table-bordered table-responsive-md table-striped text-center">
                    <tr>
                      <th class="text-center">Item type</th>
                      <th class="text-center">Picture</th>
                      <th class="text-center">Edit</th>
                    </tr>
                    {% for item_type in item_type_list %}
                    <tr>
                      <td class="pt-3-half" id="type-{{ item_type.id }}">{{ item_type.type }}</td>
                      <td class="pt-3-half"><img src="/{{ item_type.image }}" alt="" border="3" height="50" width="50" /></td>
                      <td>
                        <span class="table-edit" id="{{ item_type.id }}"><button type="button" class="btn btn-warning btn-rounded btn-sm my-0">Edit</button></span>
                      </td>
                    </tr>
                    {% endfor %}
                  </table>
                </div>
        </div>
    </div>

{% endblock %}


{% block extra_js %}
<script>
    var $TABLE = $('#table');

    $('.table-add').click(function () {
            let url = '/items/add-type/';
            window.location.assign(url);
    });

    $('.table-edit').click(function () {
            let url = '/items/update-type/' + this.id;
            window.location.assign(url);
});
</script>
{% endblock %}

wappie/templates/items/item_update_form.html
{% extends 'default.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block html_title %}
    {{ block.super }} - Edit Item
{% endblock %}

{#{% block content_title %}Edit Item{% endblock %}#}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/bootstrap-datetimepicker.css' %}">
{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script src="{% static 'scripts/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'scripts/items/items.js' %}"></script>
{% endblock %}

{% block body_left %}

<form method="post" id="itemForm" item-room-url="{% url 'buildings:floor_rooms' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update" class="btn btn-primary">
    <input type="submit" value="Cancel" class="btn btn-secondary" name="cancel">
    <input type="submit" value="Delete" class="btn btn-danger" name="delete">
</form>

{% endblock %}


{% block extra_js %}
    <script type="text/javascript">
        $(document).ready(function() {
            $(".datetimeinput").datetimepicker({
                format: "yyyy-mm-dd hh:ii:ss"
            });
        });

        getRoomsOfFloor();
    </script>
{% endblock %}

wappie/templates/items/items.html
{% extends 'default.html' %}
{% load static %}

{% block html_title %}
    {{ block.super }} - Item Types
{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/items/items.css' %}">
{% endblock %}


{% block body_main %}
{#    Items #}
    <h4>Items</h4>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ formats.0|upper }}
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% for format in formats %}
                <button class="dropdown-item" >{{ format|upper }}</button>
            {% endfor %}
        </div>
        <button class="btn btn-primary btn-white-text export">Export</button>
    </div>

    <hr/>
{#    Item types #}
    <h4>Item types</h4>
    <div class="row">
        <div class="col">
                <div id="table" class="table-editable">
                  <a href="{% url 'items:add_type' %}" class="btn btn-success btn-rounded btn-sm my-0 float-right mb-3 mr-2">Add</a>
                  <table class="table table-bordered table-responsive-md table-striped text-center">
                    <tr>
                      <th class="text-center">Item type</th>
                      <th class="text-center">Picture</th>
                      <th class="text-center">Edit</th>
                    </tr>

                    {% for item_type in item_types %}
                    <tr>
                      <td class="pt-3-half" id="type-{{ item_type.id }}">{{ item_type.type }}</td>
                      <td class="pt-3-half"><img src="/media/{{ item_type.image }}" alt="" border="3" height="50" width="50" /></td>
                      <td>
                          <a href="{% url 'items:update_type' pk=item_type.id %}" type="button" class="btn btn-outline-warning btn-rounded btn-sm my-0">Edit</a>
                      </td>
                    </tr>
                    {% endfor %}
                  </table>
                </div>
        </div>
    </div>
{% endblock %}


{% block extra_js %}
    <script>
        if (!String.prototype.trim) {
            String.prototype.trim = function () {
                return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g, '');
            };
        }
        $(".dropdown-item").on('click', function() {
            const selectedText = $(this).text();
            $('.dropdown').find('.dropdown-toggle').html(selectedText + ' ');
        });

        $(".export").on('click', function() {
            const selectedText = $(".dropdown-toggle").text();
            window.location = "{% url 'items:export' %}?format=" + selectedText.trim().toLowerCase();
        })
    </script>

{% endblock %}

wappie/templates/items/itemtype_add_form.html
{% extends 'default.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block html_title %}
    {{ block.super }} - Add Item Type
{% endblock %}

{#{% block content_title %}Add Item Type{% endblock %}#}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/bootstrap-datetimepicker.css' %}">
{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script src="{% static 'scripts/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'scripts/items/items.js' %}"></script>
{% endblock %}

{% block body_left %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

<form novalidate method="post" action="{% url 'items:add_type' %}" id="itemTypeForm" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
    <input type="submit" value="Cancel" class="btn btn-secondary" name="cancel">
</form>


{% endblock %}

wappie/templates/items/itemtype_update_form.html
{% extends 'default.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block html_title %}
    {{ block.super }} - Edit Item Type
{% endblock %}

{#{% block content_title %}Add Item Type{% endblock %}#}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/bootstrap-datetimepicker.css' %}">
{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script src="{% static 'scripts/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'scripts/items/items.js' %}"></script>
{% endblock %}

{% block body_left %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

<form novalidate method="post" id="itemTypeForm" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
    <input type="submit" value="Cancel" class="btn btn-secondary" name="cancel">
    <input type="submit" value="Delete" class="btn btn-danger btn-rounded" name="delete">
</form>


{% endblock %}

wappie/templates/items/room_dropdown_menu.html
<option value="">-------</option>
{% for room in rooms %}
    <option value="{{ room.pk }}">{{ room.room_code }}</option>
{% endfor %}