wappie/buildings/urls.py
from django.urls import path

from buildings.views import overview, building, floor_items, show_item, buildingLocation, \
    floor_rooms, room_info, floor_geojson

app_name = 'buildings'

urlpatterns = [
    path('', overview, name='index'),
    path('room', room_info, name='room_info'),
    path('rooms/', floor_rooms, name='floor_rooms'),

    path('json/', floor_geojson, name='geojson'),

    path('<slug:building_name>/', building, name='building'),
    path('<slug:building_name>/location', buildingLocation, name='building_location'),
    path('<slug:building_name>/<int:floor_number>', building, name='building_floor'),
    path('<slug:building_name>/<int:floor_number>/items', floor_items, name='floor_items'),

    path('item_details/', show_item, name='item_details'),

]

wappie/items/urls.py
from django.urls import path

from items.views import ItemUpdate, delete, replace, ItemCreate, history, items, export
from items.type_views import ItemTypeCreate, ItemTypeUpdate, item_type_delete

app_name = 'items'

urlpatterns = [
    path('', items, name='index'),

    # Items
    path('edit/<int:pk>', ItemUpdate.as_view(), name='edit'),
    path('delete/<int:pk>', delete, name='delete'),
    path('replace/<int:pk>', replace, name='replace'),
    path('add/', ItemCreate.as_view(), name='add'),
    path('history/<int:pk>', history, name='history'),
    path('export', export, name='export'),

    # Item Types
    path('types/add/', ItemTypeCreate.as_view(), name='add_type'),
    path('types/update/<int:pk>', ItemTypeUpdate.as_view(), name='update_type'),
    path('types/delete/<int:pk>', item_type_delete, name='delete_type'),
]

wappie/wappie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from wappie.views import index

urlpatterns = [
    # Home page
    path('', index, name='home'),

    # Apps
    path('buildings/', include('buildings.urls'), name='buildings'),
    path('items/', include('items.urls'), name='items'),

    # Admin
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wappie/templates/segments/header.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-primary navbar-dark">
    <a class="navbar-brand" href="{% url 'home' %}">WAPPIE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse vr" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        {% with request.resolver_match.app_name as app %}
            <li class="nav-item {% if app == 'buildings' %}active{% endif %}">
                <a class="nav-link" href="{% url 'buildings:index' %}">Map</a>
            </li>
            <li class="nav-item {% if app == 'items' %}active{% endif %}">
                <a class="nav-link" href="{% url 'items:index' %}">Types</a>
            </li>
        {% endwith %}
        </ul>
    </div>
    <div><h6 class="text-info"><small>WiFi Access Point Platform for Improved Editing</small></h6></div>
</nav>