wappie/buildings/urls.py
from django.urls import path

from buildings.views import overview, building, floor_items, show_item, buildingLocation, \
    floor_rooms, room_info, floor_geojson

app_name = 'buildings'

urlpatterns = [
    path('', overview, name='index'),
    path('room', room_info, name='room_info'),
    path('rooms/', floor_rooms, name='floor_rooms'),

    path('json/', floor_geojson, name='geojson'),

    path('<slug:building_name>/', building, name='building'),
    path('<slug:building_name>/location', buildingLocation, name='building_location'),
    path('<slug:building_name>/<int:floor_number>', building, name='building_floor'),
    path('<slug:building_name>/<int:floor_number>/items', floor_items, name='floor_items'),

    path('item_details/', show_item, name='item_details'),

]

wappie/items/urls.py
from django.urls import path

from items.views import ItemUpdate, delete, replace, ItemCreate, history, items, export
from items.type_views import ItemTypeCreate, ItemTypeUpdate, item_type_delete

app_name = 'items'

urlpatterns = [
    path('', items, name='index'),

    # Items
    path('edit/<int:pk>', ItemUpdate.as_view(), name='edit'),
    path('delete/<int:pk>', delete, name='delete'),
    path('replace/<int:pk>', replace, name='replace'),
    path('add/', ItemCreate.as_view(), name='add'),
    path('history/<int:pk>', history, name='history'),
    path('export', export, name='export'),

    # Item Types
    path('types/add/', ItemTypeCreate.as_view(), name='add_type'),
    path('types/update/<int:pk>', ItemTypeUpdate.as_view(), name='update_type'),
    path('types/delete/<int:pk>', item_type_delete, name='delete_type'),
]

wappie/wappie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from wappie.views import index

urlpatterns = [
    # Home page
    path('', index, name='home'),

    # Apps
    path('buildings/', include('buildings.urls'), name='buildings'),
    path('items/', include('items.urls'), name='items'),

    # Admin
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wappie/buildings/models.py
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from simple_history.models import HistoricalRecords


def get_default_location():
    return [52.2400, 6.8530]


class Building(models.Model):
    abbreviation = models.CharField(
        max_length=2,
        unique=True,
        verbose_name="abbreviation",
    )
    name = models.CharField(
        max_length=30,
        unique=True,
        verbose_name="building name"
    )
    number = models.PositiveIntegerField(
        unique=True,
        verbose_name="building number"
    )
    location = ArrayField(
        base_field=models.FloatField(),
        size=2,
        # Can be blank or null: if a WAP is created but has no location yet
        default=get_default_location,
        verbose_name="location",
        help_text="this is equal to the postgresql 'point' field: tuple of floats"
    )
    history = HistoricalRecords()

    @property
    def floors(self):
        return self.floor.all().order_by('floor_number')

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<Building: {self.name} ({self.abbreviation}): {self.number}>"

    class Meta:
        ordering = ['name']


class Floor(models.Model):
    building = models.ForeignKey(
        to=Building,
        on_delete=models.PROTECT,
        related_name="floor",  # This allows you to do `building.floor` and get the related floor(s)
        verbose_name="building of floor"
    )
    floor_number = models.IntegerField(
        validators=[MaxValueValidator(200), MinValueValidator(-100)],
        verbose_name="floor number"
    )
    history = HistoricalRecords()

    def __str__(self):
        return f"{self.building.name}: {self.floor_number}"

    def __repr__(self):
        return f"<Floor: {self.building.name}.{self.floor_number}>"

    @property
    def items(self):
        return self.item.all()

    @property
    def waps(self):
        return [wap for wap in self.item.all() if hasattr(wap, 'wap')]

    @property
    def rooms(self):
        return self.room.all()

    class Meta:
        unique_together = (('building', 'floor_number'),)
        ordering = ['building__name', 'floor_number']


class Room(models.Model):
    floor = models.ForeignKey(
        to=Floor,
        on_delete=models.PROTECT,
        related_name="room",
        verbose_name="floor of building"
    )
    room_code = models.CharField(
        max_length=20,
        null=False,
        blank=False,
        verbose_name="room code"
    )
    middle_of_room_location = ArrayField(
        base_field=models.FloatField(),
        size=2,
        null=True,
        blank=True,
        verbose_name="middle_room",
        help_text="the middle of the room."
    )
    history = HistoricalRecords()

    def __str__(self):
        return self.room_code

    def __repr__(self):
        return f"<Room: {repr(self.floor)} - {self.room_code}, " \
               f"location: {self.middle_of_room_location}>"

    class Meta:
        unique_together = (('floor', 'room_code'),)
        ordering = ['floor__building__name', 'floor__floor_number', 'room_code']

wappie/buildings/views.py
import json
import urllib.request as req
from urllib.error import URLError

from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render

from buildings.models import Building, Floor, Room
from items.models import Item

BASE_URL = 'http://iotdata01.utwente.nl/cgi-bin/utrooms.cgi'


def floor_items(request, building_name, floor_number):
    if request.is_ajax():
        floor = get_object_or_404(Floor, building__name=building_name, floor_number=floor_number)
        return JsonResponse({
            'items': [{'lon': i.location[0], 'lat': i.location[1], 'id': i.id, 'type': f"{i.type.image}"}
                      if i.location else {'id': i.id} for i in floor.items]
        })
    else:
        return HttpResponse()


def show_item(request):
    if request.is_ajax():
        item_id = request.GET.get('id', '')
        item = Item.objects.get(id=item_id)
        json_response = {'item': str(item)}

        return HttpResponse(json.dumps(json_response),
                            content_type='application/json')

    return render(request, 'index.html', {'user': ''})


def floor_geojson(request):
    building_name = request.GET.get('buildingName')
    floor_number = request.GET.get('floorNumber')

    url = f"{BASE_URL}?building={building_name}&floor={floor_number}"
    try:
        contents = req.urlopen(url).read()
    except URLError:
        return HttpResponse('Could not load building, check URL')
    return JsonResponse(json.loads(contents))


def overview(request):
    request.session.pop('building_name', None)
    request.session.pop('floor_number', None)
    first_floors = Floor.objects.filter(floor_number=1)
    first_floor_items = Item.objects.filter(floor__floor_number=1)
    homeless_items = Item.objects.items_without_location()
    return render(request, 'buildings/overview.html', {'first_floors_of_buildings': first_floors,
                                                       'items_on_first_floor': first_floor_items,
                                                       'homeless_items': homeless_items})


def building(request, building_name, floor_number=1):
    request.session['building_name'] = building_name
    request.session['floor_number'] = floor_number

    b = get_object_or_404(Building, name=building_name)
    f = get_object_or_404(Floor, building__name=building_name, floor_number=floor_number)
    homeless_items = Item.objects.items_without_location()
    return render(request, 'buildings/building.html',
                  {'building': b, 'floor': f, 'homeless_items': homeless_items})


def buildingLocation(request, building_name):
    building = get_object_or_404(Building, name=building_name)
    return JsonResponse({'lat': building.location[0], 'lon': building.location[1]})


def floor_rooms(request):
    floor_id = request.GET.get('floor')
    floor = get_object_or_404(Floor, id=floor_id)
    return render(request, 'items/room_dropdown_menu.html', {'rooms': floor.rooms})


def room_info(request):
    room_id = request.GET.get('room')
    room = get_object_or_404(Room, id=room_id)
    return JsonResponse({'lat': room.middle_of_room_location[0], 'lon': room.middle_of_room_location[1]})

wappie/templates/buildings/ItemHistory.html
{% load static %}


<button onclick="closeHistoryMenu()" class="w3-bar-item w3-button w3-Large">Close &times;</button>
<h4><b>  History </b></h4><p id="itemIdParagraph"></p>
<ul class="list-unstyled" id="history-list">
</ul>

wappie/templates/buildings/building.html
{% extends 'default.html' %}
{% load static %}
{% load building_extras %}

{% block html_title %}
    {{ block.super }} - {{ building.name }}
{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/overview/overview.css' %}">
{% endblock %}

{% block body_title %}{% endblock %}

{% block content_title %}{% endblock %}


{% block body_main  %}
    <!--<h2>My Map</h2>-->
    <div class="row">
        <div class="col">
                <title> {{ building.name }} </title>
        </div>
        <div class="col border-right">
            <div class="row" id="floors"></div>
        </div>
    </div>
    <div id="map" class="map" ondragover="allowDrop(event)" ondrop="handleDrop(event)"></div>

{% endblock %}

{% block body_right %}
    {% include 'buildings/overview_right.html' %}
{% endblock %}

{% block extra_js %}
    <script src="{% static 'scripts/overview.js' %}"></script>
    <script src="{% static 'scripts/drag-drop.js' %}"></script>
    <script src="{% static 'scripts/items/history.js' %}"></script>

    <script> loadBuildingView('{{ building.name }}')</script>

    <script>
        $(document).ready(function(){
            loadFirstFloor();
            {% for floor in building.floors %}
                createButton('{{ floor.floor_number }}');
            {% endfor %}
            });

        setBuildingName('{{ building.name }}');
        setFloorNumber('{{ floor.floor_number }}');


        const button_classes="btn btn-secondary floor-button";


        function createButton(floor_number, disabled=false) {
            let text = disabled ? " disabled" : "";
            let $input = $('<input onclick=loadItemsAndFloor(' + floor_number + ') type="button" class="' + button_classes + '" value="' + floor_number + '"/> ');
            $input.appendTo($('#floors'));
        }


        function loadFirstFloor() {
            load_floor_on_map('{% url 'buildings:geojson' %}?buildingName={{ building.name }}&floorNumber={{ floor.floor_number }}');
            {% for item in floor.items %}
                load_items_on_map('{{ item.location.0 }}', '{{ item.location.1 }}', {{item.id}}, '/{{ item.type.image }}');
                setupBuildingPage('{{ building.name }}', '{{ floor.floor_number }}');
            {% endfor %}
        }


        function loadItemsAndFloor(floor_number, building_name) {
            let $all_buttons = $(this).parent().children();
                for (let i = 0; i < $all_buttons.length; i++) {
                    $($all_buttons[i]).removeClass('active');
                }
                $(this).addClass('active');

            removeAllFloorLayers();
            removeAllItemLayers();
            load_floor_on_map('{% url 'buildings:geojson' %}?buildingName={{ building.name }}&floorNumber=' + floor_number);
            history.pushState(null, null, floor_number);

            setBuildingName('{{ building.name }}');
            setFloorNumber(floor_number);

            $.ajax({
                url: "/buildings/{{ building.name }}/" + floor_number + '/items',
                success: function (data) {
                    if (data) {
                        let items = data.items;
                        items.forEach(function buildItem(item) {
                            load_items_on_map(item.lon, item.lat, item.id, "/" + item.type);
                        });
                        setupBuildingPage('{{ building.name }}', floor_number);
                    }
                }
            });
        }

    </script>
{% endblock %}

wappie/templates/buildings/buildings.html
{% extends 'default.html' %}
{% load static %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/buildings/buildings.css' %}">
{% endblock %}

{#{% block content_title %}Buildings{% endblock %}#}

{% block body_main %}

    <div class="row">
        <div class="col">
            {% for building in building_list %}
                <button class="rol building btn btn-secondary" id="{{ building }}">
                    {{ building.name }}
                </button>
            {% empty %}
                No buildings
            {% endfor %}
        </div>
        <div class="col border-left">
            <div class="row" id="floors">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row" id="items">
            </div>
        </div>
        <div class="col border-left">
            <div class="row" id="single_item">

            </div>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script>
        const button_classes="btn btn-secondary floor-button";
        const button_items="btn btn-secondary item-button";

        function createButton(floor, building, disabled=false) {
            let text = disabled ? " disabled" : "";
            let $input = $('<input onclick=createItemsOfFloor(' + floor + ',' + building + ') type="button" class="' + button_classes + '" value="' + floor + '"/> ');
            $input.appendTo($('#floors'));
        }

        function createButtonItem(item, item_id, disabled=false) {
            let $input = $('<input onclick=showDetail(' + item_id + ') type="button" class="' + button_items + '" value="' + item + '"/> ');
            $input.appendTo($('#items'));
        }

        function showDetail(item_id) {

            $('#single_item').html('');

            $.get("{% url 'buildings:item_details' %}", {id: item_id}, function(json_response) {
                    console.log(json_response.item);
                    let $result = json_response.item
                    $('#single_item').append($result);
                })
        }


        function createItemsOfFloor(floor, building_name) {
            let $all_buttons = $(this).parent().children();
            for (let i = 0; i < $all_buttons.length; i++) {
                $($all_buttons[i]).removeClass('active');
            }
            $(this).addClass('active');

            $.ajax({
                url: "{% url 'buildings:floor_items' building_name='placeholder' floor_number=300 %}".replace(300, floor | 'placeholder', building_name),
                success: function (data) {
                    console.log(data);
                    let items = $('#items');
                    items.empty();

                    if (data) {
                        let items = data.split(',');
                        console.log(items);
                        for (let i = 0; i < items.length; i += 3) {
                            let xCoordinate = items[i];
                            let yCoordinate = items[i+1];
                            let itemId = items[i+2];
                            let coordinates = xCoordinate + ", " + yCoordinate;
                            createButtonItem(coordinates, itemId);

                        }
                    } else {
                            createButtonItem("No items", 1, false);
                    }
                }
            })
        }

        console.log('test');
        $('.building').on("click", function () {
            // A building was clicked
            let building = this.innerText.trim();  // Name of the building
            let $all_buttons = $(this).parent().children();

            for (let i = 0; i < $all_buttons.length; i++) {
                // Set all buttons to inactive
                $($all_buttons[i]).removeClass('active');
            }
            $(this).addClass('active');  // Set this buttons to active

            $.ajax({
                // Do an AJAX call to "url 'floors' " with the name of the building. The placeholder is
                // used like here: https://stackoverflow.com/questions/17832194/get-javascript-variables-value-in-django-url-template-tag
                url: "{% url 'buildings:floors' building_name='placeholder' %}".replace('placeholder', building),
                success: function (data) {
                    let floors = $('#floors');
                    floors.empty();

                    // Create a button per floor
                    if (data) {
                        let buildings = data.split(',');
                        console.log(buildings);
                        for (let i = 0; i < buildings.length; i += 2) {
                            createButton(buildings[i], buildings[i+1]);
                        }
                    } else {
                        createButton("No floors", true);
                    }
                }
            })
        });

    </script>
{% endblock %}

wappie/templates/buildings/homeless.html
{% load static %}

<button onclick="closeLeftMenu()" class="w3-bar-item w3-button w3-Large">Close &times;</button>
<br>
    <ul class="list-unstyled">
        <span class="float mb-3 mr-2"><a id="item-add-button" type="button" class="btn btn-success btn-rounded btn-sm my-0">Add Item</a></span>
        <h6><b> Items without location</b></h6>
    {% for item in homeless_items %}
        <li class="media list-group-item">
            <a class="media-body" href="{% url 'items:edit' pk=item.id %}" id="{{ item.id }}" ondragstart="dragStart(event)">
            <img src="/media/{{ item.type.image }}" height="35px" alt="Icon" class="mr-3">
                {{ item.type }}
                {% if item.location_description %}<br/><p class="location-description mt-0 mb-1">{{ item.location_description }}</p>{% endif %}
                <p class="mac mt-0 mb-1">MAC: {{ item.mac }}</p>
            </a>
        </li>
    {% endfor %}
</ul>

<script>
    $("#item-add-button").click(function () {
        let pathname = window.location.pathname;
        let currentlyOnIndex = pathname === '{% url 'buildings:index' %}';
        if (!currentlyOnIndex) {
            let urlParts = pathname.split('/');
            let buildingInformation = urlParts[2];
            let floorInformation = urlParts[3];
            if (!floorInformation)
                floorInformation = '1';

            let url = '{% url 'items:add' %}';
            if (buildingInformation)
                url += '?buildingName=' + buildingInformation;
            if (floorInformation && buildingInformation)
                url += '&floorNumber=' + floorInformation;
            window.location = url;
        }
        else {
            window.location = '{% url 'items:add' %}';
        }
    })
</script>

wappie/templates/buildings/overview.html
{% extends 'default.html' %}
{% load static %}
{% load building_extras %}

{% block html_title %}
    {{ block.super }} - Buildings
{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'stylesheets/overview/overview.css' %}">
{% endblock %}

{% block body_title %}{% endblock %}

{% block content_title %}{% endblock %}


{% block body_main %}

    <!--<h2>My Map</h2>-->
    <div id="map" class="map" ondragover="allowDrop(event)" ondrop="handleDrop(event)">
    </div>

{% endblock %}

{% block body_right %}
    {% include 'buildings/overview_right.html' %}
{% endblock %}

{% block extra_js %}
    {% csrf_token %}
    <script src="{% static 'scripts/overview.js' %}"></script>
    <script src="{% static 'scripts/drag-drop.js' %}"></script>
    <script src="{% static 'scripts/items/history.js' %}"></script>

    <script>
        $(document).ready(function() {
            {% for floor in first_floors_of_buildings %}
                load_floor_on_map('{% url 'buildings:geojson' %}?buildingName={{ floor.building.name }}&floorNumber={{ floor.floor_number }}');
            {% endfor %}
            {% for item in items_on_first_floor %}
                {% with "/images/items/"|add:item.type.image as icon_path %}
                    load_items_on_map('{{ item.location.0 }}', '{{ item.location.1 }}', '{{ item.id }}', '/{{ item.type.image }}');
                {% endwith %}
            {% endfor %}

            setupOverviewPage();
            });
    </script>
{% endblock %}

wappie/templates/buildings/overview_right.html
{% load static %}
{% load item_extras %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'stylesheets/buildings/overview-right.css' %}">
{% endblock %}

<div class="history move-menu jumbotron-fluid w3-bar-block w3-animate-right" id="historyMenu">
    {% include 'buildings/ItemHistory.html' %}
</div>

<div class="move-menu jumbotron-fluid w3-bar-block w3-animate-right" id="leftMenu">
    {% include 'buildings/homeless.html' %}
</div>

<div class="w3-light-grey">
    <button class="w3-button w3-light-grey w3-xlarge w3-right" onclick="openLeftMenu()">&#9776;</button>
</div>

<script>
    function openLeftMenu() {
      document.getElementById("leftMenu").style.display = "block";
    }

    function closeLeftMenu() {
      document.getElementById("leftMenu").style.display = "none";
    }

    function closeHistoryMenu() {
      document.getElementById("historyMenu").style.display = "none";
    }
</script>